<?php

namespace Database\Seeders;

use App\Models\SBMPTC;
use Illuminate\Database\Seeder;

class SBMPTCSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        collect($this->defaults())
            ->each(function ($data) {
                SBMPTC::create($data);
            });
    }

    protected function defaults()
    {
        return [
            // Distric I
            [
                'name' => 'Awesome Teen Center',
                'location' => 'Guimbal',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Guimbal',
                'district' => 'I',
            ],
            [
                'name' => 'Guimbal National High School',
                'location' => 'Guimbal',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Guimbal',
                'district' => 'I',
            ],
            [
                'name' => 'Municipality of Guimbal',
                'location' => 'Guimbal',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Guimbal',
                'district' => 'I',
            ],
            [
                'name' => 'Young Savers Teen Center',
                'location' => 'Igbaras',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Igbaras',
                'district' => 'I',
            ],
            [
                'name' => 'Igbaras National High School',
                'location' => 'Igbaras',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Igbaras',
                'district' => 'I',
            ],

            [
                'name' => 'Municipality of Igbaras',
                'location' => 'Igbaras',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Igbaras',
                'district' => 'I',
            ],
            [
                'name' => 'Palaca-Damilisan Teen Center',
                'location' => 'Miag-ao',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Miag-ao',
                'district' => 'I',
            ],
            [
                'name' => 'Palaca-Damilisan National High School',
                'location' => 'Miag-ao',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Miag-ao',
                'district' => 'I',
            ],
            [
                'name' => 'Municipality of Miag-ao',
                'location' => 'Miag-ao',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Miag-ao',
                'district' => 'I',
            ],
            [
                'name' => 'Kadampig Teen Center',
                'location' => 'Miag-ao',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Miag-ao',
                'district' => 'I',
            ],
            [
                'name' => 'Miag-ao National High School',
                'location' => 'Miag-ao',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Miag-ao',
                'district' => 'I',
            ],
            [
                'name' => 'Very Friendly Teen Center',
                'location' => 'Oton',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Oton',
                'district' => 'I',
            ],
            [
                'name' => 'Oton National High School',
                'location' => 'Oton',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Oton',
                'district' => 'I',
            ],
            [
                'name' => 'Municipality of Oton',
                'location' => 'Oton',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Oton',
                'district' => 'I',
            ],
            [
                'name' => 'Katagman Teen Center',
                'location' => 'Oton',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Oton',
                'district' => 'I',
            ],
            [
                'name' => 'Botong-Cabanbanan National High School',
                'location' => 'Oton',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Oton',
                'district' => 'I',
            ],
            [
                'name' => 'Duyan Teen Center',
                'location' => 'Tigbauan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Tigbauan',
                'district' => 'I',
            ],
            [
                'name' => 'Tigbauan National High School',
                'location' => 'Tigbauan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Tigbauan',
                'district' => 'I',
            ],
            [
                'name' => 'Municipality of Tigbauan',
                'location' => 'Tigbauan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Tigbauan',
                'district' => 'I',
            ],
            [
                'name' => 'Tender Loving Care Teen Center',
                'location' => 'Tubungan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Tubungan',
                'district' => 'I',
            ],
            [
                'name' => 'Tubungan National High School',
                'location' => 'Tubungan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Tubungan',
                'district' => 'I',
            ],
            [
                'name' => 'Municipality of Tigbauan',
                'location' => 'Tigbauan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Tigbauan',
                'district' => 'I',
            ],
            [
                'name' => 'Teen Center Care and Development',
                'location' => 'San Joaquin',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'San Joaquin',
                'district' => 'I',
            ],
            [
                'name' => 'Don Felix Sierra National High School',
                'location' => 'San Joaquin',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'San Joaquin',
                'district' => 'I',
            ],
            [
                'name' => 'Municipality of San Joaquin',
                'location' => 'San Joaquin',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'san Joaquin',
                'district' => 'I',
            ],
            [
                'name' => 'Lawigan Teen Center',
                'location' => 'San Joaquin',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'San Joaquin',
                'district' => 'I',
            ],
            [
                'name' => 'Lawigan National High School',
                'location' => 'San Joaquin',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'San Joaquin',
                'district' => 'I',
            ],
            [
                'name' => 'Municipality of San Joaquin',
                'location' => 'San Joaquin',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'San Joaquin',
                'district' => 'I',
            ],
            // District II
            [
                'name' => 'Rumbuha Sang Kasanag',
                'location' => 'Alimodian',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Alimodian',
                'district' => 'II',
            ],
            [
                'name' => 'Alimodian National High School',
                'location' => 'Alimodian',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Alimodia',
                'district' => 'II',
            ],
            [
                'name' => 'Municipality of Alimodian',
                'location' => 'Alimodian',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => '',
                'district' => '',
            ],
            [
                'name' => 'BukasPalad',
                'location' => 'Alimodian',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Alimodian',
                'district' => 'II',
            ],
            [
                'name' => 'Bancal National High School',
                'location' => 'Alimodian',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Alimodian',
                'district' => 'II',
            ],
            [
                'name' => 'Tilipunan Teen Center',
                'location' => 'Leganes',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Leganas',
                'district' => 'II',
            ],
            [
                'name' => 'Leganes National Teen Center',
                'location' => 'Leganes',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Leganes',
                'district' => 'II',
            ],
            [
                'name' => 'Municipality of Leganes',
                'location' => 'Leganes',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Leganes',
                'district' => 'II',
            ],
            [
                'name' => 'Agubay Teen Center',
                'location' => 'Leon',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Leon',
                'district' => 'II',
            ],
            [
                'name' => 'Leon National High School',
                'location' => 'Leon',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Leon',
                'district' => 'II',
            ],
            [
                'name' => 'Municipality of Leon',
                'location' => 'Leon',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Leon',
                'district' => 'II',
            ],
            [
                'name' => 'Dorog Teen Center',
                'location' => 'Leon',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Leon',
                'district' => 'II',
            ],
            [
                'name' => 'Our Lady of Peace and Good Vorage Teen Center',
                'location' => 'New Lucena',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'New Lucena',
                'district' => 'II',
            ],
            [
                'name' => 'New Lucena National High School',
                'location' => 'New Lucena',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'New Lucena',
                'district' => 'II',
            ],
            [
                'name' => 'Municipality of New Lucena',
                'location' => 'New Lucena',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'New Lucena',
                'district' => 'II',
            ],
            [
                'name' => 'Teens Nook Teen Center',
                'location' => 'Pavia',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Pavia',
                'district' => 'II',
            ],
            [
                'name' => 'Pavia National Comprehensive High School',
                'location' => 'Pavia',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Pavia',
                'district' => 'II',
            ],
            [
                'name' => 'Municipality of Pavia',
                'location' => 'Pavia',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Pavia',
                'district' => 'II',
            ],
            [
                'name' => 'Cradle of Hope Teen Center',
                'location' => 'San Miguel',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'San Miguel',
                'district' => 'II',
            ],
            [
                'name' => 'Leonora Salapan National High School',
                'location' => 'San Miguel',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'San Miguel',
                'district' => 'II',
            ],
            [
                'name' => 'Municipality of San Miguel',
                'location' => 'San Miguel',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'San Miguel',
                'district' => 'II',
            ],
            [
                'name' => 'Life\'s Journey Teen Center',
                'location' => 'Sta. Barbara',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Sta. Barbara',
                'district' => 'II',
            ],
            [
                'name' => 'Sta. Barbara National Comprehensive High School',
                'location' => 'Sta. Barbara',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Sta. Barbara',
                'district' => 'II',
            ],
            [
                'name' => 'Municipality of Sta. Barbara',
                'location' => 'Sta. Barbara',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Sta. Barbara',
                'district' => 'II',
            ],
            [
                'name' => 'Kabugwason Teen Center',
                'location' => 'Zarraga',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Zarraga',
                'district' => 'II',
            ],
            [
                'name' => 'Zarraga National High School',
                'location' => 'Zarraga',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Zarraga',
                'district' => 'II',
            ],
            [
                'name' => 'Municipality of Zarraga',
                'location' => 'Zarraga',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Zarraga',
                'district' => 'II',
            ],
            // District III
            [
                'name' => 'The Teen Zone',
                'location' => 'Badiangan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Badiangan',
                'district' => 'III',
            ],
            [
                'name' => 'Badiangan National High School',
                'location' => 'Badiangan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Badiangan',
                'district' => 'III',
            ],
            [
                'name' => 'Municipality of Badiangan',
                'location' => 'Badiangan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Badiangan',
                'district' => 'III',
            ],
            [
                'name' => 'Teen\'s Nest',
                'location' => 'Badiangan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Badiangan',
                'district' => 'III',
            ],
            [
                'name' => 'Tina National High School',
                'location' => 'Badiangan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Badiangan',
                'district' => 'III',
            ],
            [
                'name' => 'Centro La Juvenes de Bingawan',
                'location' => 'Bingawan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Bingawan',
                'district' => 'III',
            ],
            [
                'name' => 'Bingawan National High School',
                'location' => 'Bingawan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Bingawan',
                'district' => 'III',
            ],
            [
                'name' => 'Municipality of Bingawan',
                'location' => 'Bingawan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Bingawan',
                'district' => 'III',
            ],
            [
                'name' => 'Cabatuan Teen Center',
                'location' => 'Cabatuan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Cabatuan',
                'district' => 'III',
            ],
            [
                'name' => 'Cabatuan National Comprehensive High School',
                'location' => 'Cabatuan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Cabatuan',
                'district' => 'III',
            ],
            [
                'name' => 'Municipality of Cabatuan',
                'location' => 'Cabatuan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Cabatuan',
                'district' => 'III',
            ],
            [
                'name' => 'Tiring Teen Center',
                'location' => 'Cabatuan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Cabatuan',
                'district' => 'III',
            ],
            [
                'name' => 'Tiring National High School',
                'location' => 'Cabatuan',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Cabatuan',
                'district' => 'III',
            ],
            [
                'name' => 'TEENiran',
                'location' => 'Calinog',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Calinog',
                'district' => 'III',
            ],
            [
                'name' => 'Calinog Nation Comprehensive High School',
                'location' => 'Calinog',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Calinog',
                'district' => 'III',
            ],
            [
                'name' => 'Municipality of Calinog',
                'location' => 'Calinog',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => 'Calinog',
                'district' => 'III',
            ],
            [
                'name' => '',
                'location' => '',
                'tc_coordinator_count' => 0,
                'population' => 0,
                'services' => '',
                'municipality' => '',
                'district' => '',
            ],
        ];
    }
}
